models/blog.py
from . import ModelMixin
from . import db
import time
from . import timestamp


# relationtable = db.Table('relationtable',
#                          db.Column('blog_id', db.Integer, db.ForeignKey('blogs.id')),
#                          db.Column('tag_id', db.Integer, db.ForeignKey('tags.id'))
#                          )

class Blog(db.Model, ModelMixin):
    __tablename__ = 'blogs'
    id = db.Column(db.Integer, primary_key=True)
    # title = db.Column(db.String(100))
    # content = db.Column(db.String(8000))
    title = db.Column(db.String())
    picture = db.Column(db.String())
    abstract = db.Column(db.String())
    content = db.Column(db.String())
    upcount = db.Column(db.Integer)
    downcount = db.Column(db.Integer)
    created_time = db.Column(db.Integer)
    updated_time = db.Column(db.Integer)
    # has relationship with comments 一对多关系(Comment是类名)
    comments = db.relationship('Comment', backref="blog")
    messages = db.relationship('Message', backref="blog")

    # 多对多关系
    # tags = db.relationship('Tag', secondary=relationtable, backref="blogs")

    # 一对一的关系用外键（users tags是表名）
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    tag_id = db.Column(db.Integer, db.ForeignKey('tags.id'))

    def __init__(self, form):
        self.title = form.get('title', '')
        self.content = form.get('content', '')
        self.upcount = int(form.get('upcount', 0))
        self.downcount = int(form.get('downcount', 0))
        self.abstract = form.get('abstract', '')
        self.picture = r'http://res.myform.com/mmexport1446764829446.jpg'
        self.created_time = int(time.time())
        self.updated_time = int(time.time())

    def update(self, form):
        self.title = form.get('title', '')
        self.content = form.get('content', '')
        self.tag_id = form.get('tag_id', '')
        self.updated_time = int(time.time())
        self.save()

    def json(self):
        d = dict(
            title=self.title,
            content=self.content,
            upcount=self.upcount,
            downcount=self.downcount,
            created_time=self.created_time,
            updated_time=self.updated_time,
        )
        return d

models/tag.py
from . import ModelMixin
from . import db
from . import timestamp


class Tag(db.Model, ModelMixin):
    __tablename__ = 'tags'
    id = db.Column(db.Integer, primary_key=True)
    # name = db.Column(db.String(20))
    name = db.Column(db.String())

    # has relationship with comments 一对多关系(Blog是类名)
    blogs = db.relationship('Blog', backref="tag")

    def __init__(self, form):
        self.name = form.get('name', '')

    def update(self, form):
        self.name = form.get('name', '')
        self.save()

routes/blog.py
from models.blog import Blog
from models.tag import Tag
from routes import *
from routes.user import admin_required, current_user
from util.upload import upload
from models import db
import math

main = Blueprint('blog', __name__)

Model = Blog
PER_PAGE = 3


@main.route('/', defaults={'page':1})
@main.route('/page/<int:page>')
def index(page):
    # ms = Model.query.all()
    pagination = Model.query.order_by(Blog.created_time.desc()).paginate(page, PER_PAGE, False)
    total = pagination.total/PER_PAGE
    total = int(math.ceil(total))
    ts = Tag.query.all()
    if current_user():
        u = current_user()
        uid = u.id
    else:
        uid = 0
    return render_template('blog_index.html', pagination=pagination, total=total, tag_list=ts, uid=uid)


@main.route('/new')
@admin_required
def new():
    ts = Tag.query.all()
    return render_template('blog_new.html', tag_list=ts)


@main.route('/<int:id>')
def show(id):
    m = Model.query.get(id)
    ts = Tag.query.all()
    if current_user():
        u = current_user()
        uid = u.id
    else:
        uid = 0
    return render_template('blog.html', blog=m, tag_list=ts, uid=uid)


@main.route('/edit/<id>')
@admin_required
def edit(id):
    b = Model.query.get(id)
    ts = Tag.query.all()
    return render_template('blog_edit.html', blog=b, tag_list=ts)


@main.route('/pic/<id>')
@admin_required
def edit_pic(id):
    b = Model.query.get(id)
    return render_template('blog_edit_pic.html', id=b.id)


@main.route('/editpic/<id>', methods=['POST'])
def change_pic(id):
    if not upload():
        flash(u"请上传结尾为'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'的文件")
    filename = upload()
    print('debug filename, ', filename)
    b = Model.query.get(id)
    b.picture = r'http://res.myform.com/' + filename
    b.save()
    return redirect(url_for('.show',id=id))


@main.route('/add', methods=['POST'])
def add():
    form = request.form
    m = Model(form)
    m.user_id = current_user().id
    m.tag_id = int(form.get('tag_id'))
    # m.tag_id = Tag.query.filter_by(name=tag).first()
    m.save()
    return redirect(url_for('blog.show', id=m.id))


@main.route('/update/<int:id>', methods=['POST'])
def update(id):
    form = request.form
    t = Model.query.get(id)
    t.update(form)
    return redirect(url_for('blog.show', id=id))


@main.route('/delete/<int:id>')
def delete(id):
    t = Model.query.get(id)
    t.delete()
    return redirect(url_for('blog.show', id=id))

routes/message.py
from models.message import Message
from models.blog import Blog
from models.comment import Comment
from routes import *
from routes.user import admin_required, current_user


main = Blueprint('message', __name__)

Model = Message


@main.route('/cmsg')
def send_c_msg(cu, u, blog_id):
    m = Model()
    b = Blog.query.get(blog_id)
    m.message = cu.username + '评论了您的文章' + b.title
    m.user_id = u.id
    m.blog_id = blog_id
    m.save()
    print('debug m,', m, m.message, m.status)
    return 'OK'


@main.route('/rmsg')
def send_r_msg(cu, u, comment_id, blog_id):
    m = Model()
    c = Comment.query.get(comment_id)
    m.message = cu.username + '回复了您的评论' + c.content
    m.user_id = u.id
    m.blog_id = blog_id
    m.save()
    print('debug m,', m, m.message, m.status)
    return 'OK'


@main.route('/show/<int:user_id>')
def show(user_id):
    u = current_user()
    msgs = Message.query.filter_by(status=0,user_id=u.id).all()
    return render_template('msgs.html', msgs=msgs)

routes/tag.py
from models.tag import Tag
from models.blog import Blog
from routes import *
from routes.user import admin_required, current_user


main = Blueprint('tag', __name__)

Model = Tag


@main.route('/')
def index():
    ms = Model.query.all()
    u = current_user()
    return render_template('tag_index.html', tag_list=ms, uid = u.id)


@main.route('/new')
@admin_required
def new():
    return render_template('tag_new.html')


@main.route('/<int:id>')
def show(id):
    print('show tag, ', id, type(id))
    m = Model.query.get(id)
    t = Model.query.all()
    print(id, m)
    return render_template('tag.html', tag=m, tag_list=t)


@main.route('/edit/<id>')
@admin_required
def edit(id):
    t = Model.query.get(id)
    return render_template('tag_edit.html', tag=t)


@main.route('/add', methods=['POST'])
def add():
    form = request.form
    m = Model(form)
    m.save()
    return redirect(url_for('.index'))


@main.route('/update/<int:id>', methods=['POST'])
def update(id):
    form = request.form
    t = Model.query.get(id)
    t.update(form)
    return redirect(url_for('.index'))


@main.route('/delete/<int:id>')
@admin_required
def delete(id):
    t = Model.query.get(id)
    t.delete()
    return redirect(url_for('.index'))

routes/user.py
from models.user import User
# from models.topic import Topic
from routes import *
from flask import request, redirect, url_for
# for decorators
from functools import wraps
from util.upload import upload


main = Blueprint('user', __name__)

Model = User


def current_user():
    uid = session.get('uid')
    if uid is not None:
        u = User.query.get(uid)
        return u


def admin_required(f):
    @wraps(f)
    def function(*args, **kwargs):
        # your code
        print('admin required')
        u = current_user()
        uid = u.id
        # if request.args.get('uid') != '1':
        if uid != 1:
            print('not admin')
            abort(404)
        return f(*args, **kwargs)
    return function


@main.route('/')
def index():
    # ms = Model.query.all()
    return render_template('auth_index.html')


@main.route('/show/<int:id>')
def show(id):
    m = Model.query.get(id)
    return render_template('auth_show.html', user=m)


@main.route('/login', methods=['POST'])
def login():
    form = request.form
    u = User(form)
    user = Model.query.filter_by(username=u.username).first()
    if u.valid_login(user):
        session.permanent = True
        session['uid'] = user.id
        return redirect('/')
    else:
        return redirect(url_for('.index'))


@main.route('/logout')
def logout():
    # remove the uid from the session if it's there
    session.pop('uid', None)
    return redirect(url_for('user.index'))


@main.route('/register', methods=['POST'])
def register():
    form = request.form
    u = User(form)
    if u.valid():
        u.save()
        session.permanent = True
        session['uid'] = u.id
        return redirect('/user')
    else:
        return redirect(url_for('.index'))


@main.route('/avatar')
def cgavatar():
    return render_template('change_avatar.html')


@main.route('/edit-avatar', methods=['POST'])
def change_avatar():
    if not upload():
        flash(u"请上传结尾为'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'的文件")
    filename = upload()
    u = current_user()
    u.avatar = r'http://res.myform.com/' + filename
    u.save()
    flash(u'头像修改成功')
    return redirect(url_for('.show',id=u.id))

templates/auth_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>auth</title>
</head>
<body>
    <div>
        <form action="{{ url_for('.register') }}" method="post">
            <input type="text" name="username" placeholder="输入 name,长度必须大于等于 6">
            <input type="text" name="password" placeholder="输入 password,长度必须大于等于 6">
            <button>注册</button>
        </form>
    </div>
    <div>
        <form action="{{ url_for('.login') }}" method="post">
            <input type="text" name="username" placeholder="输入 name">
            <input type="text" name="password" placeholder="输入 password">
            <button>登录</button>
        </form>
    </div>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/bbs.css') }}">
    {% block css %}{% endblock %}

    <script src="/static/js/jquery-3.0.0.min.js"></script>
    {% block script %}{% endblock %}
</head>
<body>
    <div class="bbs-top">
        <a class="gua-nav-link" href="">child_education</a>
        <nav class="bbs-menu">
            <a class="gua-nav-link gua-active" href="/">首页</a>
            <a class="gua-nav-link" href="/user">注册</a>
            <a class="gua-nav-link" href="/user">登录</a>
            <a class="gua-nav-link" href="/user//logout">登出</a>
        </nav>
    </div>
    <div class="bbs-main">
        <div class="bbs-content bbs-box">
            {% block content %}
            {% endblock %}
        </div>
        <div class="bbs-sidebar bbs-box">
            <div class="bbs-sidebar-0">
                <a class="gua-nav-link" href="/user">注册登录</a>
                <a class="gua-nav-link" href="/user/logout">登出</a>
                {% if g.user %}
                    <a href="{{ url_for('message.show', user_id=g.user.id) }}">{{ g.count }}</a>
                {% endif %}
            </div>
            <div class="bbs-sidebar-0">
                {% block sidebar %}
                {% endblock %}
            </div>
            <div class="bbs-sidebar-0">
                {% block tag %}
                {% endblock %}
            </div>
        </div>
    </div>

    <div class="bbs-bottom">
        <div class="bbs-bottom-content bbs-content-size">
            <div class="bbs-bottom-nav">
                <a href="#">关于</a>
                <span>&nbsp;·&nbsp;</span>
                <a href="#">FAQ</a>
                <span>&nbsp;·&nbsp;</span>
                <a href="#">鸣谢</a>
                <span>&nbsp;·&nbsp;</span>
                <a href="#">友情链接</a>
            </div>
            <div class="bbs-bottom-about">
                创意工作者们的社区<br>World is powered by solitude
            </div>
        </div>
    </div>
</body>
</html>

templates/blog_edit.html
{% extends "base.html" %}

{% block title %}
    编辑博客
{% endblock %}

{% block content %}
    <div>
        <form action="{{ url_for('.update', id=blog.id) }}" method="post">
            <input type="text" name="tag_id" value="{{ blog.tag_id }}">
            <input type="text" name="title" value="{{ blog.title }}">
            <input type="text" name="abstract" value="{{ blog.abstract }}">
            <input type="text" name="content" value="{{ blog.content }}">
            <button>更新</button>
        </form>
    </div>
{% endblock %}

{% block sidebar %}
    <h1>放置二维码 </h1>
{% endblock %}

{% block tag %}
    {% for t in tag_list %}
        <a href="{{ url_for('tag.show', id=t.id) }}"><h2>{{ t.id }} {{ t.name }}</h2></a>
    {% endfor %}
{% endblock %}

templates/blog_edit_pic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑描述性图片</title>
</head>
<body>
    <form action="{{ url_for('.change_pic', id=id) }}" method=post enctype=multipart/form-data>
         <input type=file name=file>
         <input type=submit value=上传>
    </form>
</body>
</html>

templates/blog_index.html
{% extends "base.html" %}

{% block title %}
    blogs
{% endblock %}

{% block content %}
    {% if pagination %}
        {% for b in pagination.items %}
            <a href="{{ url_for('.show', id=b.id) }}"><h1>标题 {{ b.title }}</h1></a>
            <h4> 作者: <a href="{{ url_for('user.show', id=b.user.id) }}"><img src="{{ b.user.avatar }}" width="50" height="50"></a> 标签: {{ b.tag.name }} 时间:{{ b.created_time }} {{ b.upcount }}人点赞</h4>
            <p>内容 {{ b.content }}</p>
        {% endfor %}
        {% if pagination.has_prev %} {# 分页的前端展示 #}
            <a href="{{ url_for('blog.index', page=pagination.prev_num) }}"><< 前一页</a>
            {% else %}
            << ...
        {% endif %}
        {% for i in range(total) %}
            <a href="{{ url_for('blog.index', page=i + 1 ) }}">{{ i + 1 }}</a>
        {% endfor %}
        {% if pagination.has_next %}
            <a href="{{ url_for('blog.index', page=pagination.next_num) }}">后一页 >></a>
            {% else %}
            ... >>
        {% endif %}
    {% else %}
        <p style="color:blue;">the guy is so lazy.....</p>
    {% endif %}
{% endblock %}

{% block sidebar %}
    {% if uid == 1 %}
    <a href="{{ url_for('.new') }}">
        发布新文章
    </a>
    {% endif %}
    <h1>放置二维码 </h1>
{% endblock %}
{% block tag %}
    {% for t in tag_list %}
        <a href="{{ url_for('tag.show', id=t.id) }}"><h2>{{ t.name }}</h2></a>
        {% if uid == 1 %}
            <a href="{{ url_for('tag.edit', id=t.id) }}">
                更改
            </a>
            <a href="{{ url_for('tag.delete', id=t.id) }}">
                删除
            </a>
        {% endif %}
    {% endfor %}
{% endblock %}

templates/blog_new.html
{% extends "base.html" %}

{% block title %}
    发帖
{% endblock %}

{% block content %}
    <form action="{{ url_for('blog.add') }}" method="post">
        <input type="text" name="tag_id" placeholder="输入 tag_id">
        <br>
        <input type="text" name="upcount" placeholder="输入初始点赞数">
        <br>
        <input type="text" name="title" placeholder="输入 title">
        <br>
        <textarea type="text" name="content" placeholder="输入 content"></textarea>
        <br>
        <button>Add</button>
    </form>
{% endblock %}


{% block sidebar %}
    <h1>hello </h1>
    <a href="/tag/new">发布新标签</a>
{% endblock %}
{% block tag %}
    {% for t in tag_list %}
        <h2>{{ t.id }} {{ t.name }}</h2>
    {% endfor %}
{% endblock %}

templates/change_avatar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>更换头像</title>
</head>
<body>
<h1>选择头像文件</h1>
<form action="{{ url_for('.change_avatar') }}" method=post enctype=multipart/form-data>
    <input type=file name=file>
     <input type=submit value=上传>
</form>
</body>
</html>

templates/msgs.html
{% extends "base.html" %}

{% block title %}
    Msgs
{% endblock %}

{% block script %}
    <script src="../../static/js/api.js"></script>
    <script src="../../static/js/msg.js"></script>
{% endblock %}

{% block content %}
{% for m in msgs %}
    <span class="a-msgs-link" data-id={{ m.id }}>{{ m.message }}</span>
{% endfor %}
{% endblock %}

templates/tag.html
{% extends "base.html" %}

{% block title %}
    标签
{% endblock %}

{% block content %}
    {% for b in tag.blogs %}
    <div>
        <a href="{{ url_for('blog.show', id=b.id) }}">
            {{ b.title }}
        </a>
    </div>
    {% endfor %}
{% endblock %}

{% block sidebar %}
    <h1>放置二维码 </h1>
{% endblock %}
{% block tag %}
    {% for t in tag_list %}
        <a href="{{ url_for('tag.show', id=t.id) }}"><h2>{{ t.name }}</h2></a>
    {% endfor %}
{% endblock %}

templates/tag_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑标签</title>
</head>
<body>
    <div>
        <form action="{{ url_for('.update', id=tag.id) }}" method="post">
            <input type="text" name="name" value="{{ tag.name }}">
            <button>更新</button>
        </form>
    </div>
</body>
</html>

templates/tag_index.html
{% extends "base.html" %}

{% block title %}
    tags
{% endblock %}

{% block content %}
    <div>
        <form action="{{ url_for('.add') }}" method="post">
            <input type="text" name="name" placeholder="输入 name">
            <button>Add</button>
        </form>
    </div>

    {% for tag in tag_list %}
    <div>
        <a style="text-decoration: none" href="{{ url_for('tag.show', id=tag.id) }}">{{ tag.id }}:{{ tag.name }}</a>
    </div>
    {% if uid == 1 %}
    <a style="text-decoration: none" href="{{ url_for('.edit', id=tag.id) }}">
        更改
    </a>
    <a style="text-decoration: none" href="{{ url_for('.delete', id=tag.id) }}">
        删除
    </a>
    {% endif %}
    {% endfor %}
{% endblock %}


{% block sidebar %}
    <h1>hello </h1>
    {% if uid == 1 %}
    <a href="{{ url_for('blog.new') }}">发布新帖子</a>
    {% endif %}
{% endblock %}

templates/tag_new.html
{% extends "base.html" %}

{% block title %}
    添加标签
{% endblock %}

{% block content %}
    <form action="{{ url_for('.add') }}" method="post">
        <input type="text" name="name" placeholder="输入 name">
        <button>Add</button>
    </form>
{% endblock %}


{% block sidebar %}
    <h1>hello </h1>
    <a href="/new">发布新帖子</a>
{% endblock %}

templates/todo_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>todo edit</title>
</head>
<body>
    <div>
        <!-- action="/todo/update/{{todo.id}}" -->
        <form action="{{ url_for('.update', id=todo.id) }}" method="post">
            <input type="text" name="task" value="{{ todo.task }}">
            <button>更新</button>
        </form>
    </div>
</body>
</html>

templates/todo_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>todo</title>
    <style>
        form {
            display: inline-block;
        }
    </style>
</head>
<body>
    <div>
        <form action="{{ url_for('.add') }}" method="post">
            <input type="text" name="task" placeholder="输入 todo">
            <button>Add</button>
        </form>
    </div>

{% for todo in todo_list %}
    <div>
        <a href="{{ url_for('.edit', id=todo.id) }}">修改</a>
        <a href="{{ url_for('.delete', id=todo.id) }}">删除</a>
        {{ todo.task }}
    </div>
{% endfor %}

</body>
</html>